# eksctl create cluster -f cluster.yaml
# eksctl delete cluster -f cluster.yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cakely
  region: eu-west-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1

git:
  repo:
    url: "git@github.com:cakely/api-ops.git"
    branch: master
    fluxPath: "flux/"
    user: "imjohnbo"
    email: "imjohnbo@github.com"
  operator:
    namespace: "flux"
    withHelm: false
