---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cakely-api
  labels:
    app: cakely-api
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: cakely-api
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: cakely-api
    spec:
      containers:
      - name: cakely-api
        image: 00000000000000.dkr.ecr.my-region.amazonaws.com/example-eks:tag
        env:
        - name: APP_ID
          value: api
        - name: PORT
          value: '3000'
        - name: LOG_LEVEL
          value: debug
        - name: REQUEST_LIMIT
          value: 100kb
        - name: SESSION_SECRET
            # valueFrom:
            #   secretKeyRef:
            #     name: a-secret-store
            #     key: KEY
          value: secret
        - name: OPENAPI_SPEC
          value: /api/v1/spec
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
